name: Publish all tags to Docker Hub

on:
  workflow_dispatch: # Can be manually triggered
  push:
    branches: [ main ]
    paths-ignore:
      - 'docker-compose*.yml'
      - 'README*'
      - 'docs/**'
      - '.github/**'
      - '!.github/workflows/on-push.yml'

jobs:

  build-publish-slim:
    environment: Publish to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - 
        name: Git checkout
        uses: actions/checkout@v3
      - 
        name: Build 'slim'
        id: build-image-slim
        uses: redhat-actions/buildah-build@v2
        with:
          oci: false
          context: .
          containerfiles: Dockerfile.slim
          image: yanwk/barotrauma-server
          tags: slim
      - 
        name: Push to Docker Hub
        id: push-to-dockerhub
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
