name: Publish all tags to Docker Hub

on:
  workflow_dispatch: # Can be manually triggered
  push:
    branches: [ main ]
    paths-ignore:
      - 'docker-compose*.yml'
      - 'README*'
      - 'docs/**'
      - '.github/**'
      - '!.github/workflows/on-push.yml'

jobs:

  build-publish-slim:
    environment: Publish to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - 
        name: Git checkout
        uses: actions/checkout@v3
      - 
        name: Build 'slim'
        id: build-image-slim
        uses: redhat-actions/buildah-build@v2
        with:
          oci: false
          context: .
          containerfiles: Dockerfile.slim
          image: lightbluecube/barotrauma-server
          tags: slim
      - 
        name: Save image as tar
        run: |
          buildah pull localhost/lightbluecube/barotrauma-server:slim
          buildah save --format docker-dir localhost/lightbluecube/barotrauma-server:slim slim-image.tar
      - 
        name: Upload image artifact
        uses: actions/upload-artifact@v3
        with:
          name: slim-image
          path: slim-image.tar
